#!/bin/bash

PROGRAM=${PROGRAM:-busca_sequencial_mpi}
PROCESSOR_COUNT=${PROCESSOR_COUNT:-2}
COMPILER=${COMPILER:-cpp}

clear
rm ${PROGRAM}

echo "Compilando ${PROGRAM} em ${COMPILER}"

case "${COMPILER}" in
    c)
        mpicc -o ${PROGRAM} ${PROGRAM}.c
    ;;
    cpp)
        mpic++ -o ${PROGRAM} ${PROGRAM}.cpp
    ;;
    *)
        echo "Compilador inválido"
        exit 1
    ;;
esac

echo "Iniciando ${PROGRAM} com ${PROCESSOR_COUNT} processors"

mpirun -np ${PROCESSOR_COUNT} --hostfile host_file ${PROGRAM}
